name: CI/CD

on:
    push:
        branches:
            - main
jobs:
    docker_build:
        runs-on: ubuntu-latest
        name: build_docker
        steps: 
            - uses: actions/checkout@v4
            - name: login_dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: build_app
              uses: docker/build-push-action@v5
              with:
                context: ./
                push: true
                tags: anabelweb/anabelsantana.web:latest
    deploy:
        runs-on: ubuntu-latest
        name: continuos_deployment
        needs: [docker_build]
        steps:
            - name: remove_containers
              uses: appleboy/ssh-action@master
              with: 
                host:  ${{ secrets.HOST_IP }}
                username:  ${{ secrets.HOST_USERNAME }}
                password:  ${{ secrets.HOST_PASSWORD }}
                port: 22
                script: |
                    docker stop $(docker ps -q);docker rm $(docker ps -a -q);
            - name: remove_images
              uses: appleboy/ssh-action@master
              with: 
                host:  ${{ secrets.HOST_IP }}
                username:  ${{ secrets.HOST_USERNAME }}
                password:  ${{ secrets.HOST_PASSWORD }}
                port: 22
                script: |
                    docker rmi $(docker images -q);
            - name: deploy
              uses: appleboy/ssh-action@master
              with: 
                host:  ${{ secrets.HOST_IP }}
                username:  ${{ secrets.HOST_USERNAME }}
                password:  ${{ secrets.HOST_PASSWORD }}
                port: 22
                script: |
                    docker pull anabelweb/anabelsantana.web:latest;
                    docker run -d \
                    -p 8443:4321 \
                    -t anabelweb/anabelsantana.web:latest;
